server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: t1-java-demo
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost:5432}/school?currentSchema=t1_demo"
    username: ${DB_USER:t1}
    password: ${DB_PASSWORD:0000}
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: T1-DEMO-POOL
      auto-commit: false
      max-lifetime: 0
      minimum-idle: 2
      maximum-pool-size: 5
  liquibase:
    enabled: true
    contexts: test
    default-schema: t1_demo
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-table: t1$database_change_log
    database-change-log-lock-table: t1$database_change_log_lock

t1-demo:
  metric:
    limit-time-ms: 50
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    listener:
      ack-mode: manual_immediate
      poll-timeout: 5000
      concurrency: 1
      micrometer-enabled: true
      batch-listener: true
      error-handler:
        interval: 1000
        max-attempts: 3
    producers:
      transaction_accept:
        topic: t1_demo_transaction_accept
        acks: all
        retries: 3
        retry-backoff-ms: 1000
        enable-idempotence: false
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      metric:
        topic: t1_demo_metrics
        acks: all
        retries: 3
        retry-backoff-ms: 1000
        enable-idempotence: false
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumers:
      account:
        topic: t1_demo_accounts
        group-id: t1-account-group
        enable-auto-commit: false
        auto-offset-reset: earliest
        max-poll-records: 1
        max-poll-interval-ms: 3000
        session-timeout-ms: 15000
        max-partition-fetch-bytes: 300000
        type-dto: ru.t1.java.demo.dto.AccountDto
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.t1.java.demo.kafka.MessageDeserializer
      transaction_result:
        topic: t1_demo_transaction_result
        group-id: t1-transaction-result-group
        enable-auto-commit: false
        auto-offset-reset: earliest
        max-poll-records: 1
        max-poll-interval-ms: 3000
        session-timeout-ms: 15000
        max-partition-fetch-bytes: 300000
        type-dto: ru.t1.java.demo.dto.TransactionResultDto
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.t1.java.demo.kafka.MessageDeserializer
      transaction:
        topic: t1_demo_transactions
        group-id: t1-transaction-group
        enable-auto-commit: false
        auto-offset-reset: earliest
        max-poll-records: 1
        max-poll-interval-ms: 3000
        session-timeout-ms: 15000
        max-partition-fetch-bytes: 300000
        type-dto: ru.t1.java.demo.dto.TransactionDto
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.t1.java.demo.kafka.MessageDeserializer